### ISSUE TITLE
VisualState not disposed when page is popped

### ISSUE THREAD

**Issue by bobbybonifacia** [exrin/Exrin#16]
When the page is pushed and popped multiple times, ModelState property changes are propagated also to old instances of VisualState, which were not disposed correctly.
Adding a VisualState.Disposing call to ViewModel.Disposing() method is a workaround for the issue.

**Comment by adamped** [comment]
I'll add this to the Disposing method of the ViewModel.

var state = VisualState as BindableModel;
state?.Dispose();

Since you have an easy workaround for the moment, I won't create a new package on nuget just yet, just for 1 bug. But the code is checked in, and will be released with the next Exrin version.
