### ISSUE TITLE
Improvement: save navigation arguments (view key and stack identifier) for the page in ViewModel

### ISSUE THREAD

**Issue by bobbybonifacia** [exrin/Exrin#4]
It would be nice to have some "way" to get view navigation arguments in a ViewModel.
An example of usage: assume we have an app with two navigation stacks:

- Main: normal app pages
- Authorization stack: for login flow (multiple pages like "login", "registration", "password forgotten", etc.)

Assume we have "login" buttons on multiple pages in Main stack. Login button triggers navigation to the login page in authorization stack. When login is successfully finished, we would like to navigate back to the Main stack, to the latest view.
This can be achieved, if the view, which triggers navigation, passes its navigation arguments as navigation parameters. Than on successful authorization the navigation "back" to the page in the main stack is performed from login page in authorization stack (the arguments are saved in OnNavigated() method).

**Comment by adamped** [comment]
@bobbybonifacia - the OnNavigated does provide an args parameter that is passed through, from ViewModel to ViewModel. Could you explain how you are navigating at the moment and what api method you want the parameter to be passed to?

**Comment by bobbybonifacia** [comment]
Sorry, my explanation is a bit confusing. I will try to be more clear:
we have two navigation stacks: MainStack and LoginStack. On MainStack we have two pages: PageA and PageB. On LoginStack we have a LoginPage.
Both PageA and PageB have Login button, which should trigger the navigation to LoginPage in LoginStack.
After user is successfully logged in, he should be automatically navigated back to the previous page. The question is, how the LoginPage can find out, which page triggered the login?
One solution would be to pass the page identifiers (Stack and view) via navigation parameters to the login page, so it can grab them in OnNavigated method and perform needed navigation on success.
But how the pages A and B know, which navigation arguments do they have? 
Exrin is very flexible and allows to have one page in multiple stacks and multiple page instances in one stack (just with different view keys). In order to keep this flexibility and make each page "aware" of its current navigation args, I would suggest the following:
- in IViewModel add a method SetPageNavigationArguments(key, stack)
- in ViewModel introduce two protected properties: NavigationKey and NavigationStack and set them in SetPageNavigationArguments method.
- in BaseStack implementation, when the new page is pushed to the stack, call SetPageNavigationArguments on its ViewModel.
Than each ViewModel, which derives from Exrin one, will have its current navigation arguments and can pass them to the pages in another stacks.

**Comment by adamped** [comment]
@bobbybonifacia - there are 2 ways to go about this. First, each stack maintains its state. Meaning that if you move back to a stack, without declaring which page it should go to, it will just appear at the last page that was open.

Since stacks, shouldn't be aware of each other's state, if you need to keep this state, I would store a value in the ModelState. Any other ViewModel or Model can use this state later on, by just injecting the state.

e.g. If the login pages have ViewModel's that use AuthModel. When the Login Page goes to login, store the state in the AuthModel. Inject the AuthModel into any other ViewModel that needs this information.

Another option, is the current args you can use when you navigate at the moment you just pass through, could be of different types. Such as PageAArgs and PageBArgs.

Then you can just do, 

if (args is PageAArgs)

elseif (args is PageBArgs)

**Comment by adamped** [comment]
Assuming this is closed. Reopen if you still have an issue.
